"""baseline: service schema

Revision ID: 13713dc07ce8
Revises:
Create Date: 2026-07-23 17:29:46.018475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13713dc07ce8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_employee_code', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_employee_code', sa.String(length=40), nullable=True),
    sa.Column('detail', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='service'
    )
    op.create_index(op.f('ix_service_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False, schema='service')
    op.create_index(op.f('ix_service_admin_audit_logs_actor_employee_code'), 'admin_audit_logs', ['actor_employee_code'], unique=False, schema='service')
    op.create_index(op.f('ix_service_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False, schema='service')
    op.create_index(op.f('ix_service_admin_audit_logs_target_employee_code'), 'admin_audit_logs', ['target_employee_code'], unique=False, schema='service')
    op.create_table('clients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('business_registration_number', sa.String(length=30), nullable=True),
    sa.Column('contact_name', sa.String(length=80), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_registration_number'),
    sa.UniqueConstraint('company_name'),
    schema='service'
    )
    op.create_table('dashboard_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_code', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('count_label', sa.String(length=30), nullable=False),
    sa.Column('count_bg', sa.String(length=20), nullable=False),
    sa.Column('count_color', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('foot_note', sa.String(length=120), nullable=False),
    sa.Column('action_to', sa.String(length=120), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_code'),
    schema='service'
    )
    op.create_table('dashboard_insights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('note_color', sa.String(length=20), nullable=True),
    sa.Column('tag', sa.String(length=80), nullable=False),
    sa.Column('tag_bg', sa.String(length=20), nullable=False),
    sa.Column('tag_color', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section', 'display_order', name='uq_dashboard_insight_order'),
    schema='service'
    )
    op.create_table('employees',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'LOCKED', 'DISABLED', name='employeestatus', native_enum=False, length=20), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auth_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='service'
    )
    op.create_index(op.f('ix_service_employees_employee_code'), 'employees', ['employee_code'], unique=True, schema='service')
    op.create_table('requirements_analysis_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('raw_request', sa.Text(), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('SUCCEEDED', 'FAILED', name='analysisstatus', native_enum=False, length=20), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='service'
    )
    op.create_index(op.f('ix_service_requirements_analysis_runs_requested_by'), 'requirements_analysis_runs', ['requested_by'], unique=False, schema='service')
    op.create_index(op.f('ix_service_requirements_analysis_runs_status'), 'requirements_analysis_runs', ['status'], unique=False, schema='service')
    op.create_table('system_dashboard_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_code', sa.String(length=60), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_code'),
    schema='service'
    )
    op.create_table('data_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_no', sa.String(length=40), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('requester_name', sa.String(length=100), nullable=True),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('business_purpose', sa.Text(), nullable=True),
    sa.Column('raw_requirement', sa.Text(), nullable=False),
    sa.Column('output_formats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('delivery_channels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('usage_period', sa.String(length=200), nullable=True),
    sa.Column('analysis_condition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sample_email', sa.String(length=254), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['service.clients.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['service.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_no'),
    schema='service'
    )
    op.create_index(op.f('ix_service_data_requests_client_id'), 'data_requests', ['client_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_data_requests_owner_id'), 'data_requests', ['owner_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_data_requests_status'), 'data_requests', ['status'], unique=False, schema='service')
    op.create_table('employee_permissions',
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_code', sa.Enum('EMPLOYEE_READ', 'EMPLOYEE_CREATE', 'EMPLOYEE_UPDATE', 'EMPLOYEE_PERMISSION_MANAGE', 'EMPLOYEE_SESSION_MANAGE', 'AUDIT_READ', 'DATA_PRODUCT_READ', 'DATA_PRODUCT_WRITE', 'QUOTE_READ', 'QUOTE_PROCESS', 'CONTRACT_MANAGE', name='permissioncode', native_enum=False, length=40), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['service.employees.id'], ),
    sa.PrimaryKeyConstraint('employee_id', 'permission_code'),
    schema='service'
    )
    op.create_table('login_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('remember_me', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['service.employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token_hash'),
    schema='service'
    )
    op.create_index('idx_session_employee', 'login_sessions', ['employee_id'], unique=False, schema='service')
    op.create_index('idx_session_expires_at', 'login_sessions', ['expires_at'], unique=False, schema='service')
    op.create_table('contracts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_request_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_no', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('billing_type', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('renewed_from_id', sa.BigInteger(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_request_id'], ['service.data_requests.id'], ),
    sa.ForeignKeyConstraint(['renewed_from_id'], ['service.contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contract_no'),
    schema='service'
    )
    op.create_index(op.f('ix_service_contracts_data_request_id'), 'contracts', ['data_request_id'], unique=False, schema='service')
    op.create_index('uq_contracts_one_active', 'contracts', ['data_request_id'], unique=True, schema='service', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('pipeline_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_request_id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('current_stage', sa.String(length=80), nullable=True),
    sa.Column('progress_percent', sa.SmallInteger(), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_request_id'], ['service.data_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_request_id', 'attempt_no', name='uq_pipeline_run_attempt'),
    schema='service'
    )
    op.create_index(op.f('ix_service_pipeline_runs_current_stage'), 'pipeline_runs', ['current_stage'], unique=False, schema='service')
    op.create_index(op.f('ix_service_pipeline_runs_data_request_id'), 'pipeline_runs', ['data_request_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_pipeline_runs_status'), 'pipeline_runs', ['status'], unique=False, schema='service')
    op.create_table('task_view_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_request_id', sa.BigInteger(), nullable=False),
    sa.Column('view_code', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_request_id'], ['service.data_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_request_id', 'view_code', name='uq_task_view'),
    schema='service'
    )
    op.create_index(op.f('ix_service_task_view_snapshots_data_request_id'), 'task_view_snapshots', ['data_request_id'], unique=False, schema='service')
    op.create_table('contract_api_keys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_last4', sa.String(length=4), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['service.contracts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='service'
    )
    op.create_index(op.f('ix_service_contract_api_keys_contract_id'), 'contract_api_keys', ['contract_id'], unique=False, schema='service')
    op.create_table('stage_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=False),
    sa.Column('retry_of_id', sa.BigInteger(), nullable=True),
    sa.Column('stage_code', sa.String(length=80), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executor', sa.String(length=30), nullable=False),
    sa.Column('executor_reference', sa.String(length=255), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['service.pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['retry_of_id'], ['service.stage_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id', 'stage_code', 'attempt_no', name='uq_stage_run_attempt'),
    schema='service'
    )
    op.create_index(op.f('ix_service_stage_runs_executor_reference'), 'stage_runs', ['executor_reference'], unique=False, schema='service')
    op.create_index(op.f('ix_service_stage_runs_pipeline_run_id'), 'stage_runs', ['pipeline_run_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_stage_runs_retry_of_id'), 'stage_runs', ['retry_of_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_stage_runs_stage_code'), 'stage_runs', ['stage_code'], unique=False, schema='service')
    op.create_index(op.f('ix_service_stage_runs_status'), 'stage_runs', ['status'], unique=False, schema='service')
    op.create_table('agent_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('stage_run_id', sa.BigInteger(), nullable=False),
    sa.Column('agent_name', sa.String(length=120), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stage_run_id'], ['service.stage_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service'
    )
    op.create_index(op.f('ix_service_agent_metrics_agent_name'), 'agent_metrics', ['agent_name'], unique=False, schema='service')
    op.create_index(op.f('ix_service_agent_metrics_created_at'), 'agent_metrics', ['created_at'], unique=False, schema='service')
    op.create_index(op.f('ix_service_agent_metrics_stage_run_id'), 'agent_metrics', ['stage_run_id'], unique=False, schema='service')
    op.create_table('api_usage_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.BigInteger(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['service.contract_api_keys.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service'
    )
    op.create_index(op.f('ix_service_api_usage_logs_api_key_id'), 'api_usage_logs', ['api_key_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_api_usage_logs_requested_at'), 'api_usage_logs', ['requested_at'], unique=False, schema='service')
    op.create_table('artifacts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_run_id', sa.BigInteger(), nullable=True),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('pii_scan_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['service.pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['stage_run_id'], ['service.stage_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key'),
    schema='service'
    )
    op.create_index(op.f('ix_service_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False, schema='service')
    op.create_index(op.f('ix_service_artifacts_pipeline_run_id'), 'artifacts', ['pipeline_run_id'], unique=False, schema='service')
    op.create_table('pipeline_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pipeline_run_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_run_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['service.pipeline_runs.id'], ),
    sa.ForeignKeyConstraint(['stage_run_id'], ['service.stage_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service'
    )
    op.create_index(op.f('ix_service_pipeline_events_event_type'), 'pipeline_events', ['event_type'], unique=False, schema='service')
    op.create_index(op.f('ix_service_pipeline_events_occurred_at'), 'pipeline_events', ['occurred_at'], unique=False, schema='service')
    op.create_index(op.f('ix_service_pipeline_events_pipeline_run_id'), 'pipeline_events', ['pipeline_run_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_pipeline_events_stage_run_id'), 'pipeline_events', ['stage_run_id'], unique=False, schema='service')
    op.create_table('deliveries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_request_id', sa.BigInteger(), nullable=False),
    sa.Column('artifact_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('recipient', sa.String(length=254), nullable=True),
    sa.Column('secret_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['service.artifacts.id'], ),
    sa.ForeignKeyConstraint(['data_request_id'], ['service.data_requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service'
    )
    op.create_index(op.f('ix_service_deliveries_artifact_id'), 'deliveries', ['artifact_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_deliveries_data_request_id'), 'deliveries', ['data_request_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_deliveries_status'), 'deliveries', ['status'], unique=False, schema='service')
    op.create_table('reviews',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('data_request_id', sa.BigInteger(), nullable=False),
    sa.Column('stage_run_id', sa.BigInteger(), nullable=True),
    sa.Column('artifact_id', sa.BigInteger(), nullable=True),
    sa.Column('reviewer_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True),
    sa.Column('review_type', sa.String(length=40), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['service.artifacts.id'], ),
    sa.ForeignKeyConstraint(['data_request_id'], ['service.data_requests.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['service.employees.id'], ),
    sa.ForeignKeyConstraint(['stage_run_id'], ['service.stage_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='service'
    )
    op.create_index(op.f('ix_service_reviews_artifact_id'), 'reviews', ['artifact_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_reviews_data_request_id'), 'reviews', ['data_request_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False, schema='service')
    op.create_index(op.f('ix_service_reviews_stage_run_id'), 'reviews', ['stage_run_id'], unique=False, schema='service')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_reviews_stage_run_id'), table_name='reviews', schema='service')
    op.drop_index(op.f('ix_service_reviews_reviewer_id'), table_name='reviews', schema='service')
    op.drop_index(op.f('ix_service_reviews_data_request_id'), table_name='reviews', schema='service')
    op.drop_index(op.f('ix_service_reviews_artifact_id'), table_name='reviews', schema='service')
    op.drop_table('reviews', schema='service')
    op.drop_index(op.f('ix_service_deliveries_status'), table_name='deliveries', schema='service')
    op.drop_index(op.f('ix_service_deliveries_data_request_id'), table_name='deliveries', schema='service')
    op.drop_index(op.f('ix_service_deliveries_artifact_id'), table_name='deliveries', schema='service')
    op.drop_table('deliveries', schema='service')
    op.drop_index(op.f('ix_service_pipeline_events_stage_run_id'), table_name='pipeline_events', schema='service')
    op.drop_index(op.f('ix_service_pipeline_events_pipeline_run_id'), table_name='pipeline_events', schema='service')
    op.drop_index(op.f('ix_service_pipeline_events_occurred_at'), table_name='pipeline_events', schema='service')
    op.drop_index(op.f('ix_service_pipeline_events_event_type'), table_name='pipeline_events', schema='service')
    op.drop_table('pipeline_events', schema='service')
    op.drop_index(op.f('ix_service_artifacts_pipeline_run_id'), table_name='artifacts', schema='service')
    op.drop_index(op.f('ix_service_artifacts_artifact_type'), table_name='artifacts', schema='service')
    op.drop_table('artifacts', schema='service')
    op.drop_index(op.f('ix_service_api_usage_logs_requested_at'), table_name='api_usage_logs', schema='service')
    op.drop_index(op.f('ix_service_api_usage_logs_api_key_id'), table_name='api_usage_logs', schema='service')
    op.drop_table('api_usage_logs', schema='service')
    op.drop_index(op.f('ix_service_agent_metrics_stage_run_id'), table_name='agent_metrics', schema='service')
    op.drop_index(op.f('ix_service_agent_metrics_created_at'), table_name='agent_metrics', schema='service')
    op.drop_index(op.f('ix_service_agent_metrics_agent_name'), table_name='agent_metrics', schema='service')
    op.drop_table('agent_metrics', schema='service')
    op.drop_index(op.f('ix_service_stage_runs_status'), table_name='stage_runs', schema='service')
    op.drop_index(op.f('ix_service_stage_runs_stage_code'), table_name='stage_runs', schema='service')
    op.drop_index(op.f('ix_service_stage_runs_retry_of_id'), table_name='stage_runs', schema='service')
    op.drop_index(op.f('ix_service_stage_runs_pipeline_run_id'), table_name='stage_runs', schema='service')
    op.drop_index(op.f('ix_service_stage_runs_executor_reference'), table_name='stage_runs', schema='service')
    op.drop_table('stage_runs', schema='service')
    op.drop_index(op.f('ix_service_contract_api_keys_contract_id'), table_name='contract_api_keys', schema='service')
    op.drop_table('contract_api_keys', schema='service')
    op.drop_index(op.f('ix_service_task_view_snapshots_data_request_id'), table_name='task_view_snapshots', schema='service')
    op.drop_table('task_view_snapshots', schema='service')
    op.drop_index(op.f('ix_service_pipeline_runs_status'), table_name='pipeline_runs', schema='service')
    op.drop_index(op.f('ix_service_pipeline_runs_data_request_id'), table_name='pipeline_runs', schema='service')
    op.drop_index(op.f('ix_service_pipeline_runs_current_stage'), table_name='pipeline_runs', schema='service')
    op.drop_table('pipeline_runs', schema='service')
    op.drop_index('uq_contracts_one_active', table_name='contracts', schema='service', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_service_contracts_data_request_id'), table_name='contracts', schema='service')
    op.drop_table('contracts', schema='service')
    op.drop_index('idx_session_expires_at', table_name='login_sessions', schema='service')
    op.drop_index('idx_session_employee', table_name='login_sessions', schema='service')
    op.drop_table('login_sessions', schema='service')
    op.drop_table('employee_permissions', schema='service')
    op.drop_index(op.f('ix_service_data_requests_status'), table_name='data_requests', schema='service')
    op.drop_index(op.f('ix_service_data_requests_owner_id'), table_name='data_requests', schema='service')
    op.drop_index(op.f('ix_service_data_requests_client_id'), table_name='data_requests', schema='service')
    op.drop_table('data_requests', schema='service')
    op.drop_table('system_dashboard_snapshots', schema='service')
    op.drop_index(op.f('ix_service_requirements_analysis_runs_status'), table_name='requirements_analysis_runs', schema='service')
    op.drop_index(op.f('ix_service_requirements_analysis_runs_requested_by'), table_name='requirements_analysis_runs', schema='service')
    op.drop_table('requirements_analysis_runs', schema='service')
    op.drop_index(op.f('ix_service_employees_employee_code'), table_name='employees', schema='service')
    op.drop_table('employees', schema='service')
    op.drop_table('dashboard_insights', schema='service')
    op.drop_table('dashboard_alerts', schema='service')
    op.drop_table('clients', schema='service')
    op.drop_index(op.f('ix_service_admin_audit_logs_target_employee_code'), table_name='admin_audit_logs', schema='service')
    op.drop_index(op.f('ix_service_admin_audit_logs_created_at'), table_name='admin_audit_logs', schema='service')
    op.drop_index(op.f('ix_service_admin_audit_logs_actor_employee_code'), table_name='admin_audit_logs', schema='service')
    op.drop_index(op.f('ix_service_admin_audit_logs_action'), table_name='admin_audit_logs', schema='service')
    op.drop_table('admin_audit_logs', schema='service')
    # ### end Alembic commands ###
