-- =====================================================================
-- [V007] 익명처리 이력 테이블 — 법정 기록보존 의무 대응
--
-- 근거: 금융분야 가명·익명처리 안내서(2022.01) III.1.다 "기록보존의 의무"
--   신용정보회사등은 개인신용정보를 익명처리한 경우 다음 기록을 3년간 보존해야 한다.
--     ① 익명처리한 날짜
--     ② 익명처리한 정보의 항목
--     ③ 익명처리한 사유와 근거
--
-- 왜 mart 스키마에 두는가 (anon이 아니라):
--   이 로그에는 "어떤 기법으로 어느 수준까지 익명처리했는지"가 담긴다. 그 자체가
--   재식별 공격의 단서(어떤 컬럼이 얼마나 뭉개졌는지)가 되므로, LLM이 조회하는
--   anon 계층에 두면 안 된다. agent_svc가 접근할 수 없는 mart에 둔다.
--   ("가명처리 방법은 적지 않고 결과만 적는다"는 mart 코멘트 원칙과 같은 이유)
--
-- 실행: psql -v ON_ERROR_STOP=1 -U portfolio_admin -d portfolio \
--             -f migrations/V007__anonymization_log.sql
-- =====================================================================

BEGIN;

CREATE TABLE mart.anonymization_log (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ① 익명처리한 날짜
    executed_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at       TIMESTAMPTZ,

    -- ② 익명처리한 정보의 항목
    target_items       JSONB       NOT NULL,

    -- ③ 익명처리한 사유와 근거
    purpose            TEXT        NOT NULL,
    legal_basis        TEXT        NOT NULL,

    -- 적용 기법·수준 (적정성 평가 시 기초자료가 된다)
    techniques         JSONB       NOT NULL,
    k_value            SMALLINT    NOT NULL CHECK (k_value >= 2),
    suppressed_rows    INTEGER     NOT NULL DEFAULT 0 CHECK (suppressed_rows >= 0),

    -- 처리 결과
    row_counts         JSONB       NOT NULL,
    validation_passed  BOOLEAN     NOT NULL DEFAULT false,
    error_message      TEXT,

    -- 재현성: 어느 버전의 배치가 만들었는지
    batch_version      VARCHAR(30) NOT NULL,

    CONSTRAINT ck_anon_log_time_order CHECK (
        completed_at IS NULL OR completed_at >= executed_at
    )
);

CREATE INDEX idx_anon_log_executed ON mart.anonymization_log (executed_at DESC);

COMMENT ON TABLE mart.anonymization_log IS
'익명처리 실행 이력. 금융분야 가명·익명처리 안내서(2022.01)의 기록보존 의무(3년)에 대응한다.
배치를 실행할 때마다 1행이 쌓이며, 실패한 실행도 남는다(validation_passed=false).
보존기간이 지난 행의 정리는 별도 배치로 수행한다 — 이 테이블은 자동 삭제하지 않는다.';

COMMENT ON COLUMN mart.anonymization_log.target_items IS
'익명처리한 정보의 항목(안내서 요구사항 ②). 테이블별 처리 대상 컬럼 목록.';

COMMENT ON COLUMN mart.anonymization_log.legal_basis IS
'익명처리의 법적 근거(안내서 요구사항 ③). 예: 신용정보법 제2조제17호 익명처리.';

COMMENT ON COLUMN mart.anonymization_log.techniques IS
'적용한 익명처리 기법과 수준. 적정성 평가 시 기초자료로 사용된다.
재식별 단서가 될 수 있으므로 이 테이블은 anon이 아닌 mart에 둔다(agent_svc 접근 불가).';

COMMENT ON COLUMN mart.anonymization_log.k_value IS
'적용한 k-익명성 수준. 데이터 규모가 커지면 상향을 재검토한다.';

COMMENT ON COLUMN mart.anonymization_log.suppressed_rows IS
'로컬 억제로 준식별자가 일반화된 행 수. 손실률 추이를 관찰하는 지표.';

COMMIT;

-- =====================================================================
-- 검증
-- =====================================================================
-- SELECT executed_at, k_value, suppressed_rows, validation_passed, batch_version
--   FROM mart.anonymization_log ORDER BY executed_at DESC LIMIT 5;
