-- =====================================================================
-- [V009] automation 스키마 — Supervisor 실행 계층
-- 대상: PostgreSQL 17, portfolio DB
--
-- 실행: psql -v ON_ERROR_STOP=1 -U portfolio_admin -d portfolio \
--             -f migrations/V009__automation_schema.sql
--   ※ 반드시 portfolio_admin으로 실행 — 소유자만 이후 ALTER/TRUNCATE가 가능하다.
-- 이전: V008 (anon 컬럼 코멘트)
--
-- 전제: supervisor_svc 롤이 미리 있어야 한다(비밀번호는 저장소에 두지 않는다).
--   psql -d portfolio -c "CREATE ROLE supervisor_svc LOGIN PASSWORD '<직접입력>';"
--
-- ---------------------------------------------------------------------
-- 왜 이 파일이 필요한가
-- ---------------------------------------------------------------------
-- Supervisor(automation-supervisor-api)는 지금까지 앱 시작 시
-- `Base.metadata.create_all`로 테이블을 만들었다. 그 방식의 문제:
--
--   1) 마이그레이션 밖 — V001~V008 + Alembic 체계 어디에도 기록이 남지 않는다.
--   2) 스키마 미지정 — Base에 schema가 없어 public으로 간다.
--   3) 소유권 붕괴 — CREATE를 실행한 계정이 소유자가 된다. 우리 원칙은
--      "모든 스키마의 소유자는 portfolio_admin"이다.
--
-- 이 파일이 그 세 가지를 한 번에 해결하고, 앱에서는 create_all을 제거한다.
--
-- ---------------------------------------------------------------------
-- 왜 service가 아니라 별도 스키마인가
-- ---------------------------------------------------------------------
-- Supervisor는 FastAPI와 다른 프로세스(Celery 워커)로 실행된다.
-- service 스키마에 두면 Supervisor가 employees(비밀번호 해시)·contracts·
-- clients가 있는 스키마에 접속해야 한다. 스키마를 나누면 GRANT 한 줄로
-- 그 경계를 물리적으로 만들 수 있다.
--
-- 상태 정본은 둘로 나뉜다. 흐름은 항상 한 방향이다.
--
--   Supervisor --> automation.*         (실행 엔진의 내부 상태)
--              --> Redis 이벤트
--              --> status_subscriber
--              --> service.pipeline_*   (실무자 화면에 보여줄 상태)
--              --> SSE --> React
--
--   * Supervisor는 service.pipeline_* 를 직접 쓰지 않는다.
--   * FastAPI(app_svc)는 automation.* 를 직접 읽지 않는다.
--     -> 그래서 이 파일은 app_svc에 아무 권한도 주지 않는다. 원칙을 문서가
--        아니라 GRANT로 강제한다.
--
-- ---------------------------------------------------------------------
-- 데이터 성격 (중요)
-- ---------------------------------------------------------------------
-- 이 스키마는 "로그성 테이블"이 아니다. 실제 데이터가 쌓인다.
--   automation_jobs.raw_requirement          사용자가 입력한 원문
--   automation_stage_runs.input_payload      단계 입력 (anon 조회 결과 행 포함)
--   automation_stage_runs.output_payload     단계 출력
--   stage_artifact_caches.artifact           단계 결과 캐시
-- 따라서 보존기간·정리 정책이 필요하다(9절 참고). agent_svc에는 권한을 주지 않는다.
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 1. 스키마
-- ---------------------------------------------------------------------
CREATE SCHEMA IF NOT EXISTS automation AUTHORIZATION portfolio_admin;

-- COMMENT ON SCHEMA는 GRANT와 무관하게 누구나 조회 가능하므로 개요만 남긴다.
COMMENT ON SCHEMA automation IS
'자동화 파이프라인 실행 계층. Supervisor 워커가 소유하며 작업·단계 상태를 보관한다.
실무자 화면용 상태는 service 스키마에 따로 있다(이벤트로 동기화).';


-- ---------------------------------------------------------------------
-- 2. automation_jobs — 작업 1건
-- ---------------------------------------------------------------------
CREATE TABLE automation.automation_jobs (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    requirement_id     INTEGER,
    raw_requirement    TEXT         NOT NULL,
    status             VARCHAR(30)  NOT NULL DEFAULT 'QUEUED',
    current_stage      VARCHAR(80),
    progress_percent   INTEGER      NOT NULL DEFAULT 0,
    qa_iteration       INTEGER      NOT NULL DEFAULT 0,
    max_qa_iterations  INTEGER      NOT NULL DEFAULT 3,
    rollback_to_stage  VARCHAR(80),
    error_message      TEXT,
    final_result       JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    started_at         TIMESTAMPTZ,
    completed_at       TIMESTAMPTZ,
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_automation_jobs PRIMARY KEY (id),

    CONSTRAINT ck_automation_jobs_status CHECK (
        status IN ('QUEUED', 'RUNNING', 'WAITING_HITL', 'COMPLETED', 'FAILED', 'WAITING_RETRY')
    ),
    CONSTRAINT ck_automation_jobs_stage CHECK (
        current_stage IS NULL
     OR current_stage IN ('REQUIREMENT_ANALYSIS', 'DATA_SELECTION', 'DATA_PROCESSING', 'HITL_REVIEW')
    ),
    CONSTRAINT ck_automation_jobs_rollback CHECK (
        rollback_to_stage IS NULL
     OR rollback_to_stage IN ('REQUIREMENT_ANALYSIS', 'DATA_SELECTION', 'DATA_PROCESSING', 'HITL_REVIEW')
    ),
    CONSTRAINT ck_automation_jobs_progress CHECK (progress_percent BETWEEN 0 AND 100),
    CONSTRAINT ck_automation_jobs_qa CHECK (qa_iteration >= 0 AND qa_iteration <= max_qa_iterations),

    -- 완료 시각은 시작 시각보다 앞설 수 없다 (배치/시각 계산 버그 안전망)
    CONSTRAINT ck_automation_jobs_time_order CHECK (
        completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at
    )
);

CREATE INDEX idx_automation_jobs_requirement ON automation.automation_jobs (requirement_id);
CREATE INDEX idx_automation_jobs_status      ON automation.automation_jobs (status);
CREATE INDEX idx_automation_jobs_stage       ON automation.automation_jobs (current_stage);

COMMENT ON TABLE automation.automation_jobs IS
'Supervisor 작업 1건. 1행 = 요청 1건의 자동화 실행.
단계별 이력은 automation_stage_runs에 있다.';

COMMENT ON COLUMN automation.automation_jobs.requirement_id IS
'대응하는 service.data_requests.id.
의도적으로 FK를 걸지 않는다 — 스키마(=서비스) 간 결합을 만들면 한쪽 마이그레이션이
다른 쪽을 잠그고, Supervisor가 service 스키마 권한을 요구하게 된다. 정합성은 애플리케이션이 맡는다.';

COMMENT ON COLUMN automation.automation_jobs.raw_requirement IS
'사용자가 입력한 요구사항 원문. 개인정보가 섞여 들어올 수 있는 자유 텍스트다.
유입 시점 검사·보존기간 정책 대상(DLP 검토 문서 참고).';

COMMENT ON COLUMN automation.automation_jobs.final_result IS
'마지막 단계까지 통과한 산출물 모음. HITL 승인 대기 시점에 채워진다.';

COMMENT ON COLUMN automation.automation_jobs.rollback_to_stage IS
'HITL 반려 시 되돌아갈 단계. 반려 사유(failure_code)로 결정된다.
NULL = 되돌릴 필요 없음. 다음 실행이 시작될 때 소비되고 NULL로 되돌아간다.';


-- ---------------------------------------------------------------------
-- 3. automation_stage_runs — 단계 실행 이력
-- ---------------------------------------------------------------------
CREATE TABLE automation.automation_stage_runs (
    id                 BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    job_id             BIGINT       NOT NULL,
    stage_name         VARCHAR(80)  NOT NULL,
    status             VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    model_name         VARCHAR(120),
    input_payload      JSONB        NOT NULL DEFAULT '{}'::jsonb,
    output_payload     JSONB        NOT NULL DEFAULT '{}'::jsonb,
    validation_result  JSONB        NOT NULL DEFAULT '{}'::jsonb,
    error_message      TEXT,
    run_order          INTEGER      NOT NULL DEFAULT 0,
    started_at         TIMESTAMPTZ,
    completed_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_automation_stage_runs PRIMARY KEY (id),
    CONSTRAINT fk_automation_stage_runs_job FOREIGN KEY (job_id)
        REFERENCES automation.automation_jobs (id) ON DELETE CASCADE,

    CONSTRAINT ck_automation_stage_runs_stage CHECK (
        stage_name IN ('REQUIREMENT_ANALYSIS', 'DATA_SELECTION', 'DATA_PROCESSING', 'HITL_REVIEW')
    ),
    CONSTRAINT ck_automation_stage_runs_status CHECK (
        status IN ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ROLLED_BACK', 'CACHED')
    ),
    CONSTRAINT ck_automation_stage_runs_time_order CHECK (
        completed_at IS NULL OR started_at IS NULL OR completed_at >= started_at
    ),

    -- 실패한 단계에는 사유가 있어야 한다 (원인 추적 불가 상태 방지)
    CONSTRAINT ck_automation_stage_runs_failure CHECK (
        status <> 'FAILED' OR error_message IS NOT NULL
    )
);

CREATE INDEX idx_automation_stage_runs_job    ON automation.automation_stage_runs (job_id);
CREATE INDEX idx_automation_stage_runs_stage  ON automation.automation_stage_runs (stage_name);
CREATE INDEX idx_automation_stage_runs_status ON automation.automation_stage_runs (status);

-- 중단된 파이프라인 복구용. Celery 태스크가 유실되면 PENDING인 채로 남으므로,
-- 주기적으로 이 인덱스를 타고 찾아 재개할 수 있어야 한다.
CREATE INDEX idx_automation_stage_runs_pending
    ON automation.automation_stage_runs (created_at)
    WHERE status = 'PENDING';

COMMENT ON TABLE automation.automation_stage_runs IS
'단계 실행 이력. 1행 = 한 단계의 1회 실행. job_id로 automation_jobs에 묶인다.
Celery 태스크 하나가 이 행 하나를 처리하고, 다음 행을 만든 뒤 종료한다.';

COMMENT ON COLUMN automation.automation_stage_runs.input_payload IS
'단계에 들어간 입력. 데이터 선별 이후 단계에는 anon 조회 결과 행이 그대로 담긴다.
익명 데이터이므로 개인 식별은 불가하나, 보존기간 정책 대상이다.';

COMMENT ON COLUMN automation.automation_stage_runs.output_payload IS
'단계가 낸 출력. agent 응답 원문(JSON)이다.';

COMMENT ON COLUMN automation.automation_stage_runs.validation_result IS
'출력 검증 결과. passed 여부와 실패 시 failure_code·errors를 담는다.
failure_code가 rollback 대상 단계를 결정한다.';

COMMENT ON COLUMN automation.automation_stage_runs.status IS
'PENDING(등록만 됨) / RUNNING / COMPLETED / FAILED / ROLLED_BACK / CACHED.
CACHED = 동일 입력의 이전 결과를 재사용해 agent를 호출하지 않음.';


-- ---------------------------------------------------------------------
-- 4. stage_artifact_caches — 단계 결과 캐시
-- ---------------------------------------------------------------------
CREATE TABLE automation.stage_artifact_caches (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    stage_id    BIGINT       NOT NULL,
    cache_key   VARCHAR(128) NOT NULL,
    artifact    JSONB        NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT pk_stage_artifact_caches PRIMARY KEY (id),
    CONSTRAINT fk_stage_artifact_caches_stage FOREIGN KEY (stage_id)
        REFERENCES automation.automation_stage_runs (id) ON DELETE CASCADE
);

CREATE INDEX idx_stage_artifact_caches_stage ON automation.stage_artifact_caches (stage_id);
CREATE INDEX idx_stage_artifact_caches_key   ON automation.stage_artifact_caches (cache_key);

COMMENT ON TABLE automation.stage_artifact_caches IS
'단계 결과 캐시. 동일 입력으로 다시 실행할 때 agent 호출을 건너뛰기 위한 것.
HITL 반려 후 재실행에서 앞 단계를 재계산하지 않게 해준다.';

COMMENT ON COLUMN automation.stage_artifact_caches.cache_key IS
'단계명 + 모델명 + 입력 payload로 만든 결정적 키.
모델이 바뀌면 키도 바뀌므로 이전 모델의 결과가 재사용되지 않는다.';

COMMIT;


-- =====================================================================
-- 5. 권한 (GRANT)
-- =====================================================================
-- supervisor_svc — Supervisor 워커 전용. 이 스키마만 접근한다.
GRANT USAGE ON SCHEMA automation TO supervisor_svc;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA automation TO supervisor_svc;

ALTER DEFAULT PRIVILEGES FOR ROLE portfolio_admin IN SCHEMA automation
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO supervisor_svc;

-- 기본 노출 차단
REVOKE ALL ON SCHEMA automation FROM PUBLIC;

-- 의도적으로 권한을 주지 않는 대상 (원칙을 GRANT로 강제)
--   app_svc   : FastAPI는 automation을 직접 읽지 않는다.
--               실무자 화면 상태는 service.pipeline_* 를 본다(이벤트로 동기화됨).
--   agent_svc : 에이전트 경로는 anon만 본다. 이 스키마에는 다른 작업의
--               입력·출력이 모여 있으므로 접근시키지 않는다.


-- =====================================================================
-- 6. 검증 (실행 후 확인용)
-- =====================================================================
-- -- 소유자가 portfolio_admin인지
-- SELECT nspname, pg_get_userbyid(nspowner) FROM pg_namespace WHERE nspname='automation';
--
-- -- 테이블 3개와 소유자
-- SELECT tablename, tableowner FROM pg_tables WHERE schemaname='automation' ORDER BY 1;
--
-- -- app_svc / agent_svc 가 접근 불가인지 (둘 다 false여야 정상)
-- SELECT has_schema_privilege('app_svc','automation','USAGE') AS app_svc,
--        has_schema_privilege('agent_svc','automation','USAGE') AS agent_svc;
--
-- -- 시각 컬럼이 전부 timestamptz인지 (0줄이어야 정상)
-- SELECT table_name, column_name, data_type FROM information_schema.columns
--  WHERE table_schema='automation' AND data_type='timestamp without time zone';


-- =====================================================================
-- 7. 앱 쪽에서 함께 바꿔야 하는 것 (이 파일만으로는 끝나지 않음)
-- =====================================================================
-- 1) automation-supervisor-api/app/db/base.py
--      Base.metadata에 schema="automation" 지정
-- 2) automation-supervisor-api/app/db/session.py
--      init_db()의 create_all 제거
-- 3) automation-supervisor-api/app/main.py
--      init_db() 호출 제거
-- 4) automation-supervisor-api/app/domain/models.py
--      DateTime -> DateTime(timezone=True), utcnow() -> timezone-aware
-- 5) automation-supervisor-api/app/core/config.py
--      database_url 기본값을 appuser@appdb -> supervisor_svc@portfolio 로


-- =====================================================================
-- 8. 이미 public에 테이블이 생겨버린 경우 (정리 절차)
-- =====================================================================
-- create_all이 한 번이라도 실행됐다면 public에 같은 이름의 테이블이 있다.
-- 데이터가 없으면 그냥 지우면 된다:
--   DROP TABLE IF EXISTS public.stage_artifact_caches,
--                        public.automation_stage_runs,
--                        public.automation_jobs CASCADE;
-- 데이터가 있으면 옮긴 뒤 지운다:
--   ALTER TABLE public.automation_jobs SET SCHEMA automation;   (이하 동일)
--   ※ 옮긴 경우 타입이 timestamp(무시간대)이므로 별도 변환이 필요하다.


-- =====================================================================
-- 9. 미결 — 보존기간 정책
-- =====================================================================
-- input_payload/output_payload/artifact에는 실제 데이터가 쌓인다.
-- 무기한 보관할 이유가 없으므로 정리 주기를 정해야 한다(팀 협의 필요).
--   후보) 완료된 job은 N일 후 payload만 NULL 처리하고 상태·시각은 남긴다
--        (통계·감사는 유지하면서 데이터만 줄이는 방식)
-- 캐시(stage_artifact_caches)는 재실행 편의용이므로 더 짧게 잡아도 무방하다.
