from enum import Enum


class JobStatus(str, Enum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    WAITING_HITL = "WAITING_HITL"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    WAITING_RETRY = "WAITING_RETRY"


class StageStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"
    CACHED = "CACHED"


class StageName(str, Enum):
    REQUIREMENT_ANALYSIS = "REQUIREMENT_ANALYSIS"
    DATA_SELECTION = "DATA_SELECTION"
    DATA_PROCESSING = "DATA_PROCESSING"
    HITL_REVIEW = "HITL_REVIEW"


class FailureCode(str, Enum):
    SCHEMA_INVALID = "SCHEMA_INVALID"
    REQUIRED_KEY_MISSING = "REQUIRED_KEY_MISSING"
    FORMAT_INVALID = "FORMAT_INVALID"
    LOGICAL_CONTRADICTION = "LOGICAL_CONTRADICTION"
    MISINTERPRETED_REQUIREMENT = "MISINTERPRETED_REQUIREMENT"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    LOW_SIMILARITY_MATCH = "LOW_SIMILARITY_MATCH"
    DUPLICATED_DATA = "DUPLICATED_DATA"
    OUTLIER_DETECTED = "OUTLIER_DETECTED"
    PROCESSING_RULE_INVALID = "PROCESSING_RULE_INVALID"
    HUMAN_REJECTED = "HUMAN_REJECTED"
